M48
; DRILL file {KiCad 9.0.0} date 2025-08-15T01:25:26+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-15T01:25:26+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X105.75Y-65.4
X111.53Y-65.4
T2
X97.3Y-61.29
X100.3Y-61.29
X117.15Y-61.3
X120.15Y-61.3
X121.219Y-79.425
X121.219Y-82.425
M30
